<?php

namespace OctolizeShippingCanadaPostVendor\Octolize\Brand\UpsellingBox;

use OctolizeShippingCanadaPostVendor\WPDesk\ShowDecision\WooCommerce\ShippingMethodInstanceStrategy;
class ShippingMethodInstanceShouldShowStrategy extends ShippingMethodInstanceStrategy
{
}
